version: 0.0.{build}

configuration: Release

init:
- ps: Update-AppveyorBuild -Version "0.0.$env:appveyor_build_number-sha.$($env:appveyor_repo_commit.substring(0,7))"
- ps: Write-host $env:APPVEYOR_BUILD_VERSION

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '0.0.{build}'
  assembly_file_version: '0.0.{build}'
  assembly_informational_version: '{version}'

matrix:
  fast_finish: true # fail fast!

clone_depth: 3  

pull_requests:
  do_not_increment_build_number: true

before_build:
  nuget restore DotJEM.Json.Visitor\DotJEM.Json.Visitor.sln

build:
  project: DotJEM.Json.Visitor\DotJEM.Json.Visitor.sln
  publish_nuget: true
  publish_nuget_symbols: true

after_build:
  dir

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
